# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
referenceDocs:
  requiredPropsFirst: true
  hideHostname: true
  theme:
    colors:
      primary:
        main: "#0063c5"
    menu:
      backgroundColor: "#edf6ff"
    rightPanel:
      backgroundColor: "#153345"
