# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  gates: openapi/gates.yaml
  addresses: openapi/addresses.yaml
lint:
  extends:
    - recommended
  plugins:
    - './plugins/custom-preprocessors.js'
    - './plugins/custom-rules.js'
  preprocessors:
    custom-preprocessors/add-x-enum-to-description:
      vendorExtension: x-aviskase-enum
  rules:
    no-unused-components: warning
    no-empty-servers: off
    custom-rules/uppercase-schema-enums:
      severity: error
      enumLikeProperties:
        - x-aviskase-enum
    custom-rules/description-style:
      severity: error
referenceDocs:
  requiredPropsFirst: true
  hideHostname: true
  theme:
    colors:
      primary:
        main: "#0063c5"
    menu:
      backgroundColor: "#edf6ff"
    rightPanel:
      backgroundColor: "#153345"
