openapi: 3.0.3
info:
  version: 1.0.0
  title: Stargate Network
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  description:
    $ref: description.md
tags:
  - name: Addresses
    description: >
      A Stargate address is a coordinate system used by a Stargate to determine the position of a target gate 
      in the Stargate Network. They are composed of a series of glyphs, at least seven depending on the 
      intended destination, which when entered in the correct order allow the Stargate to establish a wormhole 
      with another gate at the destination ([source](https://stargate.fandom.com/wiki/Stargate_address)).
  - name: Stargates
    description: >
      A Stargate is a device which create wormholes, allowing for near-instantaneous transportation between 
      two distant points in space.  ([source](https://stargate.fandom.com/wiki/Stargate)).
paths:
  /addresses:
    $ref: paths/addresses.yaml
  /addresses/{id}:
    $ref: paths/addresses@{id}.yaml
  /stargates:
    $ref: paths/stargates.yaml
  /stargates/{id}:
    $ref: paths/stargates@{id}.yaml
components:
  securitySchemes:
    api_key:
      $ref: components/securitySchemes/api_key.yaml
